version: '3'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  frontend:
    image: python:3.10
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    command: bash -c "pip install -r requirements.txt && streamlit run streamlit_app.py"
